[workspace]
members = [
  "threerender",
  "threerender_entities",
  "threerender_traits",
  "threerender_math",
  "threerender_color",
  "threerender_loader",
  "shader_processor",
  "examples/*",
]
resolver = "2"
