[package]
name = "examples_common"
version = "0.1.0"
edition = "2021"
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
threerender = { path = "../../threerender" }
env_logger = "0.10.0"
winit = "0.27.5"
